### ISSUE TITLE
Volume control for Multi-Output Device

### ISSUE THREAD

**Issue by shrx** [The9Labs/AudioMate#24]
Volume control is disabled for Multi-Output Devices:

![screen shot 2016-05-03 at 23 50 17](https://cloud.githubusercontent.com/assets/810337/14999473/d8f0d47a-1189-11e6-9d52-d06ab7002cfd.png)

**Comment by rnine** [comment]
Good point. And it is also disabled for Aggregate Devices.

I'll see if I can handle such cases in v3. 

Thanks for reporting!

**Comment by rnine** [comment]
Hmm, OS X does not seem to handle these cases either.

Here's the UI for an Aggregate Device and a Multi-Output Device in HALLab (please notice how the virtual master volume is greyed out):

<img width="802" alt="screen shot 2016-05-09 at 14 55 07" src="https://cloud.githubusercontent.com/assets/479427/15113691/1f27d0ae-15f6-11e6-80fd-05d143d23578.png">
<img width="802" alt="screen shot 2016-05-09 at 14 55 09" src="https://cloud.githubusercontent.com/assets/479427/15113693/1f4e8c76-15f6-11e6-8df4-49b0432af090.png">
<img width="802" alt="screen shot 2016-05-09 at 14 55 11" src="https://cloud.githubusercontent.com/assets/479427/15113692/1f4dc9c6-15f6-11e6-9c91-159aac0c83f0.png">

And here's what happens when a Multi-Output device is set as the default output device and the "Increase Volume" and "Decrease Volume" keys are pressed:

![disabled](https://cloud.githubusercontent.com/assets/479427/15113723/4b191e34-15f6-11e6-9eeb-fc0241790274.png)

I think I'll remain consistent with this behavior.

Thanks again for your report, though!
